Cargo.lock
crates/lair_keystore/Cargo.toml
crates/lair_keystore/src/bin/lair-keystore/main.rs
crates/lair_keystore/src/store.rs
crates/lair_keystore/src/store/store_file.rs
crates/lair_keystore/tests/integration.rs
crates/lair_keystore_api/Cargo.toml
crates/lair_keystore_api/src/internal/ipc.rs
crates/lair_keystore_api/src/internal/ipc/unix_ipc.rs
crates/lair_keystore_api/src/internal/sign_ed25519.rs
crates/lair_keystore_api/src/internal/tls.rs
crates/lair_keystore_api/src/ipc.rs
crates/lair_keystore_api/src/test.rs
crates/lair_keystore_client/Cargo.toml
crates/lair_keystore_client/src/internal/run_lair_executable.rs
crates/lair_keystore_client/src/lib.rs

Looks like a straightforward migration, and `cargo test` passes locally.

[TK-05823] Update to tokio 0.3

---

Cargo.lock
crates/lair_keystore/Cargo.toml
crates/lair_keystore/src/bin/lair-keystore/main.rs
crates/lair_keystore/src/store.rs
crates/lair_keystore/src/store/store_file.rs
crates/lair_keystore/tests/integration.rs
crates/lair_keystore_api/Cargo.toml
crates/lair_keystore_api/src/internal/ipc.rs
crates/lair_keystore_api/src/internal/ipc/unix_ipc.rs
crates/lair_keystore_api/src/internal/sign_ed25519.rs
crates/lair_keystore_api/src/internal/tls.rs
crates/lair_keystore_api/src/ipc.rs
crates/lair_keystore_api/src/test.rs
crates/lair_keystore_client/Cargo.toml
crates/lair_keystore_client/src/internal/run_lair_executable.rs
crates/lair_keystore_client/src/lib.rs

Reverting https://github.com/holochain/lair/pull/17 for now - but we can re-apply when we're ready.

Revert "[TK-05823] Update to tokio 0.3"

---

README.md
docs/protocol.md

It the MVP of protocol documentation that has
- overview of message framing
- payload byte order for each request/response wire type
PS: Once we start implementing a Javascript client for this, I could add in some payload examples

Documentation for communications protocol

---

docs/protocol.md

- fix byte order for wire type to represent LE order
- replace misleading hex values with actual number values
- fix sign by pubkey wire type number

Minor fixes/changes to protocol documentation

---

crates/lair_keystore/src/ipc.rs
crates/lair_keystore_api/src/actor.rs
crates/lair_keystore_api/src/entry.rs
crates/lair_keystore_api/src/internal/ipc.rs
crates/lair_keystore_api/src/internal/wire.rs
crates/lair_keystore_api/src/test.rs

Holo's hosted infrastructure creates a lair keystore server that make signing requests to user's web browsers. These signing requests can fail, (e.g. user is not logged in) therefore we need to be able to return an error back to Holochain. Currently we just don't respond if we encounter an error, which leads to bad behavior if Holochain forgot to add a timeout.

Add ErrorResponse variant to LairWire

---

crates/lair_keystore/src/bin/lair-keystore/main.rs
crates/lair_keystore/src/lib.rs

Lair keystore is an area of a lot of confusion and some challenges for app developers, and through my own trial and errors, I've made the observations that comments like these would be helpful for the lair-keystore binary.

Add log for lair-keystore-dir and also help text for main binary + config option

---

Cargo.lock
crates/lair_keystore/Cargo.toml
crates/lair_keystore_api/Cargo.toml
crates/lair_keystore_api/src/config.rs
crates/lair_keystore_api/src/internal/ipc/win_ipc.rs
crates/lair_keystore_client/Cargo.toml
crates/lair_keystore_client/src/internal/run_lair_executable.rs

Used `tokio::named_pipe` to implement the Windows version of IPC.
`socket_path` had to be adjusted in Config for it to work properly.

Windows implementation with NamedPipes

---

crates/hc_seed_bundle/src/seed_cipher.rs
crates/hc_seed_bundle/src/seed_cipher/pw_hash_limits.rs
crates/hc_seed_bundle/src/seed_cipher/pw_utils.rs
crates/hc_seed_bundle/src/seed_cipher/seed_bundle.rs
crates/hc_seed_bundle/src/seed_cipher/u8array.rs

DEPENDS ON https://github.com/holochain/lair/pull/46
- adds utilites that make writing the seed_cipher code possible
- `pw_hash_limits` - argon2id memory and ops limit controls
- `pw_utils` - password hashing utilities
- `seed_bundle` - serialization code to translate between ergonomic rust structs and compact msgpack array format
- `u8array` - fixed-size array newtype with lots of ergonomic from impls

add seed cipher util code

---

crates/lair_keystore_api/src/config.rs
crates/lair_keystore_api/src/encoding_types.rs
crates/lair_keystore_api/src/lair_store.rs
crates/lair_keystore_api/src/lib.rs
crates/lair_keystore_api/src/mem_store.rs

DEPENDS ON https://github.com/holochain/lair/pull/62
[Video Walkthrough (2:48)](https://www.youtube.com/watch?v=kEbM_5CMklM)
We want it to be pretty easy to write a new backend store for lair, so the api the store needs to impl is pretty straight forward. Additional logic to make the store easy to work with is written into the concrete wrapper for the store trait-object.

[new-lair-4] lair store abstraction + memory implementation

---

crates/lair_keystore_api/src/lair_api.rs
crates/lair_keystore_api/src/lair_api/error.rs
crates/lair_keystore_api/src/lair_api/get_entry.rs
crates/lair_keystore_api/src/lair_api/get_wka_tls_cert_priv_key.rs
crates/lair_keystore_api/src/lair_api/hello.rs
crates/lair_keystore_api/src/lair_api/list_entries.rs
crates/lair_keystore_api/src/lair_api/new_seed.rs
crates/lair_keystore_api/src/lair_api/new_wka_tls_cert.rs
crates/lair_keystore_api/src/lair_api/sign_by_pub_key.rs
crates/lair_keystore_api/src/lair_api/unlock.rs
crates/lair_keystore_api/src/lib.rs

DEPENDS ON https://github.com/holochain/lair/pull/63
[Video Walkthrough (1:34)](https://www.youtube.com/watch?v=IhXleu8RmLM)
Start with the [LairApiEnum](https://github.com/holochain/lair/pull/64/files#diff-501c62882899456a70a744e94f56daaa560643f1428f8851276b1bc540d64a58R86) for the list of requests/responses available in the lair api, then move onto the individual struct modules for details about the parameters,
Each api struct can be marked with the marker traits `AsLairRequest` or `AsLairResponse` to facilitate the type system knowing which type will be returned from a specific request.

[new-lair-5] lair api serialization types

---

crates/lair_keystore_api/src/lair_api/sign_by_pub_key.rs
crates/lair_keystore_api/src/lair_client.rs
crates/lair_keystore_api/src/lair_client/async_io.rs
crates/lair_keystore_api/src/lib.rs

DEPENDS ON https://github.com/holochain/lair/pull/64
[Video Walkthrough (2:39)](https://www.youtube.com/watch?v=dm0g6kR7uG8)
- trait / trait-object wrapper concrete struct for making requests as a client of a lair server.
- an implementation of the above built around generic `AsyncRead / AsyncWrite` pair, which we can later use to expose a client based on ipc unix domain socket / windows named pipes

[new-lair-6] lair client abstraction and async_io implementation

---

crates/lair_keystore_api/src/lair_server.rs
crates/lair_keystore_api/src/lair_server/priv_api.rs
crates/lair_keystore_api/src/lair_server/priv_srv.rs
crates/lair_keystore_api/src/lib.rs

DEPENDS ON https://github.com/holochain/lair/pull/65
[Video Walkthrough (2:47)](https://www.youtube.com/watch?v=U5C3AGlZ6QI)
Defines an abstraction for implementing a server, as well as a concrete server implementation that is agnostic to the storage backend and how the server actually manages to communicate with the client (so long as it uses an `AsyncRead / AsyncWrite` channel).

[new-lair-7] lair server abstraction and implementation

---

crates/lair_keystore_api/src/in_proc_keystore.rs
crates/lair_keystore_api/src/ipc_keystore.rs
crates/lair_keystore_api/src/ipc_keystore/raw_ipc.rs
crates/lair_keystore_api/src/lib.rs

DEPENDS ON https://github.com/holochain/lair/pull/66
[Video Walkthrough (3:30)](https://www.youtube.com/watch?v=i3-bWkZj8sU)
Two server wrappers:
- one that uses `tokio::io::duplex` to facilitate an in-process keystore server, i.e. could be used for testing
- one that uses unix domain sockets on most systems or windows named-pipes on windows

[new-lair-8] in-process keystore + ipc keystore

---

Cargo.lock
crates/hc_seed_bundle/src/unlocked_seed_bundle.rs
crates/lair_keystore/Cargo.toml
crates/lair_keystore/src/bin/lair-keystore-bin/cmd_import_seed.rs
crates/lair_keystore/src/bin/lair-keystore-bin/cmd_init.rs
crates/lair_keystore/src/bin/lair-keystore-bin/cmd_server.rs
crates/lair_keystore/src/bin/lair-keystore-bin/main.rs
crates/lair_keystore/src/server.rs
crates/lair_keystore_api/src/ipc_keystore.rs
crates/lair_keystore_api/src/lair_server.rs
crates/lair_keystore_api/src/lair_server/priv_srv.rs

DEPENDS ON https://github.com/holochain/lair/pull/69
[Video Walkthrough (2:15)](https://www.youtube.com/watch?v=cS4KzoTg5UY)
Allow importing hc_seed_bundle bundles from quickstart / etc into a lair keystore store using the lair-keystore binary cli.

[new-lair-11] import seed_bundle lair-keystore cli command

---

.github/workflows/ops.test.yml
Cargo.lock
Makefile
crates/lair_keystore_api/Cargo.toml
crates/lair_keystore_api/src/bin/fixture-sig-fallback.rs
crates/lair_keystore_api/src/config.rs
crates/lair_keystore_api/src/in_proc_keystore.rs
crates/lair_keystore_api/src/lair_server.rs
crates/lair_keystore_api/src/lair_server/priv_api.rs
crates/lair_keystore_api/src/lair_server/priv_srv.rs

DEPENDS ON: https://github.com/holochain/lair/pull/71
[Video Walkthrough (2:46)](https://www.youtube.com/watch?v=axcQ63RojWE)
Allows specifying a signatureFallback executable in the lair server config:
```yaml
signatureFallback: none
```
or
```yaml
signatureFallback:
command:
program: "./my-executable"
args:
- test-arg1
- test-arg2
```
which will read newline delimited json requests on stdin like:
```json
{"msgId":"k9PRhnExjFK_K_kOiHT3k","pubKey":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA","dataToSign":"aGVsbG8="}
```
and is expected to respond with newline delimited responses on stdout like:
```json
{"msgId":"k9PRhnExjFK_K_kOiHT3k","signature":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="}
```
or
```json …
```

[new-lair-13] signature_fallback hook for Holo integration

---

Cargo.lock
Cargo.toml
README.md
crates/hc_seed_bundle/Cargo.toml
crates/hc_seed_bundle/src/seed_cipher.rs
crates/hc_seed_bundle/src/seed_cipher/seed_bundle.rs
crates/hc_seed_bundle/src/unlocked_seed_bundle.rs
crates/lair_keystore/Cargo.toml
crates/lair_keystore/README.md
crates/lair_keystore/src/bin/lair-keystore-bin/main.rs
crates/lair_keystore/src/docs/help.md
crates/lair_keystore/src/docs/import-seed-help.md
crates/lair_keystore/src/docs/init-help.md
crates/lair_keystore/src/docs/server-help.md
crates/lair_keystore/src/docs/url-help.md
crates/lair_keystore/src/store_sqlite.rs
crates/lair_keystore_api/Cargo.toml
crates/lair_keystore_api/src/internal/tls.rs
crates/lair_keystore_api/src/lair_server/priv_api.rs
crates/lair_keystore_api/src/lair_store.rs
crates/lair_keystore_api/src/sodium_secretstream/inner.rs

DEPENDS ON https://github.com/holochain/sodoken/pull/19
Address audit findings:
- Issue A: Tls Private Key Is Not Zeroized
- TLS private key is now zeroized and stored in a mem-secure sodoken buffer
- Suggestion 1: Update and Maintain Dependencies
- Updated Dependencies
- Suggestion 2: Do Not Panic in Drop Implementation
- Removed the panic

LA Audit Fixes

---

crates/lair_keystore_api/src/config.rs

I thought in any case this error message could be more useful. There might be various folks spinning up lair keystore processes decoupled from holochain, and they might run into it.

fixes #103 just by providing a useful failure message

---

crates/lair_keystore_api/Cargo.toml

We were relying on one of our dependencies (socket2? possibly, not sure) enabling a feature on `winapi` that we relied on. That is no longer the case. Just adding in the feature flag that gives us the module we need.

Fix compile with winapi for Windows

---

crates/lair_keystore_api/src/config.rs
crates/lair_keystore_api/tests/config.rs

When creating a new lair config on unix, ensure the param `connection_url` uses an absolute path to the unix socket.
I think this resolves an issue where `Conductor::builder().build().await` panics when passing in `None`, or a relative path for the config option `keystore.lair_root`, but still need to test.

fix: use absolute path for unix socket in connection_url 

---

Cargo.lock
crates/hc_seed_bundle/Cargo.toml
crates/lair_keystore/src/store_sqlite.rs
crates/lair_keystore_api/Cargo.toml

After the conductor API [breakage due to an interplay between `rmp-serde` and a patch update in `serde`](https://github.com/serde-rs/serde/issues/2662), these two packages are pinned in the Holochain repo. Lair is using a different version of `rmp-serde`, which is why I'd like to match the one in Holochain to prevent serialization problems between Lair and Holochain.

build: pin serde and rmp-serde

---

.github/workflows/release.yml
.github/workflows/static.yml
.github/workflows/test.yml
crates/lair_keystore/CHANGELOG.md
crates/lair_keystore/src/lib.rs
crates/lair_keystore/src/store_sqlite.rs
crates/lair_keystore/tests/common.rs
crates/lair_keystore/tests/migrate_unencrypted.rs
crates/lair_keystore/tests/server_test.rs

This is similar to the change I made [here](https://github.com/holochain/holochain/pull/2973).
I know that Lair databases are meant to be encrypted but the `lair_keystore` crate exposes the option to disable database encryption by not using default features, so it would be good if there was a way to migrate if you end up being forcibly switched by something that has embedded Lair and changed it's defaults. Looking at you Holochain :)

Automatically migrate unencrypted databases on request

---

Cargo.lock

We do this regularly in Holochain to make sure that the dependencies people will see if they build without our lock file will work with the current code on the current toolchain. It looks like it's been a while since it was done here because we aren't actively working on Lair

Update to newer dependencies to check that everything is working

---

.github/workflows/release.yml
.github/workflows/static.yml
.github/workflows/test.yml

Holochain now uses Rust 1.71.1

Bump the Rust version used by Holochain

---

Cargo.lock
Makefile
README.md
crates/hc_seed_bundle/Cargo.toml
crates/hc_seed_bundle/src/lib.rs
crates/lair_keystore/Cargo.toml
crates/lair_keystore/README.md
crates/lair_keystore/src/bin/lair-keystore-bin/main.rs
crates/lair_keystore/src/docs/help.md
crates/lair_keystore/src/docs/import-seed-help.md
crates/lair_keystore/src/docs/init-help.md
crates/lair_keystore/src/docs/server-help.md
crates/lair_keystore/src/docs/url-help.md
crates/lair_keystore/src/lib.rs
crates/lair_keystore_api/Cargo.toml
crates/lair_keystore_api/src/lib.rs

As discussed, remove deny warnings and rely on CI to catch warnings. See recommendations from clippy [docs](https://doc.rust-lang.org/stable/clippy/usage.html#command-line)
I've also bumped the versions in the same PR so I can release this once the PR is in

Remove deny warnings

---

CHANGELOG.md
Cargo.lock
crates/lair_keystore/Cargo.toml
crates/lair_keystore/src/bin/lair-keystore-bin/main.rs
crates/lair_keystore/tests/client_commands.rs

As reported in issue #137, the output of the `url` command is supposed to just be the `connection_url`. This PR sets the tracing output to `stderr` to keep `stdout` clean of logs.
Closes #137

feat: set tracing to output to stderr

---

CHANGELOG.md
Cargo.lock
Cargo.toml
crates/lair_keystore/src/pid_check.rs

This resolves an issue with building against a recent libc

fix(lair_keystore): Update `sysinfo` dependency

---

.github/workflows/test.yml
Cargo.lock
Cargo.toml
crates/lair_keystore/src/pid_check.rs

This resolves an issue with building against a recent libc

[BACKPORT 0.4.x] fix(lair_keystore): Update `sysinfo` dependency

---

.github/workflows/release.yml
.github/workflows/static.yml
.github/workflows/test.yml
CHANGELOG.md
crates/hc_seed_bundle/tests/execute_fixture_tests.rs
rust-toolchain.toml

Apparently the code here was in good shape, minimal changes needed to update to Rust 1.85

chore: Bump to Rust 1.85
